import Head from 'next/head'
import Navbar from '../components/Navbar'
import Footer from '../components/Footer'


export default function Home() {
  return (
    <>
      <Head>
        <title>steelgrey-group</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous"></link>
      </Head>
      <main >
        <Navbar />

      <section>
        <div className='container text-black p-md-'>
          <div className='row ps-0'>
            {/* show on mobile */}
          <div className='col-md-6 ui-show-only ui-hide-big ps-0'>
              <div className="pt-5 mt-4 mx-auto">        
                <img src="../../../assets/clean7.jpg" class="d-block im-fluid" alt="..."/>
                </div>
              </div>

            <div className='col-md-6 ui-hide-only'>
                <div className="pt-5 mt-4">
                    <h1 className='fs-xxxlarge lh-1 text-color mb-4'>SteelGrey Group <br /> Limited</h1>
                    <p className='pt-3 fs-normal'>Steelgrey Cleaning Specialists are on a mission to provide first class cleaning services and customer care, putting the customers needs at the forefront of all we do.</p>

                </div>
            </div>
              {/* carousel */}
              <div className='col-md-6 ui-hide-only ps-0 '>
              <div className="pt-5 mt-4">
                <img src="../../../assets/clean7.jpg" class="d-block img-fluid" alt="..."/>
                </div>
              </div>
              {/* show on laptop */}
              <div className='col-md-6 ui-show-only ui-hide-big'>
                <div className="pt-2 mt-2">
                    <h1 className='fs-xxlarge line-height text-color
                      mb-4'>SteelGrey Group cleaning <br /> service</h1>
                    <p className='pt-3 fs-normal'>Steelgrey Cleaning Specialists are on a mission to provide first class cleaning services and customer care, putting the customers needs at the forefront of all we do.</p>

                </div>
            </div>
              
          </div>
        </div>
      </section>

      {/* second session */}
      <div id='services'>
        <div className="container ">
            <hr />
           <div className="text-center">
                <h1 className='text-color my-5 fw-light fs-xxxlarge'>Solutions for every <br /> business needs</h1>
           </div>
           <div className="row ">
                <div className="col-md-4 border-0">
                    <div className="card border-0 ">
                        <div className="card-body shadow-lg p-4 mb-3">
                            <h1 className='text-color mt-2 mb-md-4'>1.</h1>
                            <h2 className='text-color my-md-5 my-sm-2'>Steelgrey Cleaning service</h2>
                            <p className='mb-4'>Get in touch with our friendly Lagos & Abuja-based cleaning company about your requirements today. Whether you’re a homeowner, tenant, landlord or corporate client, we are ready to help.</p>
                        </div>
                    </div>
                </div>
                <div className="col-md-4">
                    <div className="card border-0 ">
                        <div className="card-body shadow-lg p-4 mb-3">
                            <h1 className='text-color mt-2 mb-md-5 my-sm-2'>2.</h1>
                            <h2 className='text-color mb-md-5 mb-sm-4'>Arrange A Consultation</h2>
                            <p>For all our cleaning services, we undertake a bespoke no obligation consultation to ensure our work is tailored to your needs down to the very last detail.</p>
                        </div>
                    </div>
                </div>
                <div className="col-md-4">
                    <div className="card border-0">
                        <div className="card-body shadow-lg p-4">
                            <h1 className='text-color mt-2 mb-md-5 my-sm-2'>3.</h1>
                            <h2 className='text-color mb-3'>Get ready to Steelgrey</h2>
                            <p>Our experienced and dependable Lagos & Abuja cleaners will arrive on-time and complete your clean to the highest possible standard, leaving your property Steelgreyd. Whether you choose a one-off clean or a regular service package, we are confident you will love our results.</p>
                        </div>
                    </div>
                </div>
                {/* <div className="text-color d-flex justify-content-end my-4">
                    <h4 className='fw-normal'>Make an enquiry
                      <a href="/getStarted">
                        <img src="../../../assets/icons/arrow-right.png" alt="..." className='mx-2 arrrow-i'/>
                        </a>
                      </h4>
                </div> */}
           </div>
        </div>

        <div className="text-center">
                <h1 className='text-color mt-5 fw-light fs-xxxlarge'>Solutions for every <br /> business needs</h1>

                <button className="btn text-white bg-color fw-medium px-4 shadow-lg" type="submit">
                <a href="/getStarted">How can we help?</a>
              </button>
           </div>

            {/* <section className='happy-customer-section'>
            <div className='container text-black'>
              <div className='row'>
                <div className='col-md-10 mx-auto'>
                <h1 className='mt-5 pt-4 mb-4 text-center fs-xxxlarge text-color'>Happy Customers, Happy Homes & Happy Businesses</h1>
                  <div className="row">
                    <div className='col-md-12 mx-auto'>
                      <div>
                          <p className='fs-normal text-center '><q className=''>Tom and his team at Steelgrey were recommended to us and I’m really glad they were. They have carried out excellent work with real attention to detail. All of our clients have been delighted with their work be it end of tenancy cleans, full sterilised cleans or usual home cleans. We will certainly continue to use Tom in the future as it is so important to have reliable contractors in our industry. Thanks for the great work!</q></p>
                      </div>
                      <div>
                          <h6 className='text-color text-center my-4'>James Managing Partner Rice Chamberlains Estate Agents</h6>
                      </div>
                    </div>
              
                  </div>
                </div>
              </div>
            </div>
                </section>  */}
    </div>

    {/* third session */}
    <div className="container p-md-5 mt-5" id='about'>
            <div className="row mb-5">
                <div className="col-md-6">
                     <div className="card border-0">
                         <img src="../../../../assets/clean7.jpg" alt="..." className=''/>
                    </div>
                </div>
                <div className="col-md-6 mb-4 ">
                    <div className=" mt-3 ">
                          <h1 className='fs-xxlarge line-height text-color mb-4'>About Steelgrey Group</h1>
                          <p className='pt-3 fs-normal text-black fs-large '>At Steelgrey, we strive for excellence in everything we do. Whether we are working with a domestic client or a large corporation, we are committed to providing the highest quality cleaning services. If you are an individual with cleaning experience, have a professional attitude and a dedication to doing the best job possible, you’ll love working at Steelgrey.</p>
                      </div>
                </div>
            </div>

            <div className="row mt-md-5">
                <div className="col-md-6 mt-md-3">
                    <div className=" mt-md-3 ">
                          <h1 className='fs-xxlarge line-height text-color mb-4'>Benefits of working with Steelgrey</h1>
                          <p className='pt-3 fs-normal text-black fs-large '>We have a range of positions available at competitive rates. There are progression opportunities for our team members to build a rewarding career with us at Steelgrey too. We currently have full-time, part-time and apprentice jobs open, so please contact us for more information.</p>
                          <p className='pt-3 fs-normal text-black fs-large '>We think Steelgrey is one of the best cleaning companies to work for. If you are looking for cleaning jobs in Lagos & Abuja and the surrounding areas, we would love to have you join our team.</p>
                      </div>
                </div>
                <div className="col-md-6">
                     <div className="card border-0">
                         <img src="../../../../assets/clean3.png" alt="..." className=''/>
                    </div>
                </div>

            </div>

        </div>

      <Footer />
      </main>

     
    </>
  )
}
